#!/usr/bin/env bash
# Regenerate a PDF from Markdown, without the hang.
#
# WHY THIS EXISTS. md-to-pdf renders through headless Chrome and hangs roughly
# half the time in this environment — three times in one session, each costing a
# stalled command that had to be killed by hand. It is not wrong when it works;
# it just cannot be relied on unattended.
#
# So: try md-to-pdf with a deadline, and fall back to pandoc if it stalls.
#
# The two produce DIFFERENT-LOOKING documents, and that is the whole reason for
# the fallback order. md-to-pdf renders the HTML/CSS styling this repo's PDFs
# have always used; pandoc + tectonic typesets as LaTeX, which is perfectly
# readable but visibly not the same document. Preferring md-to-pdf keeps the
# established look when it cooperates; the fallback means an unattended run
# still produces a PDF instead of a stalled terminal.
#
# weasyprint is deliberately NOT used. It is installed here and it fails
# SILENTLY — leaving the previous PDF in place, so the file still exists, its
# timestamp looks plausible at a glance, and the content is stale. A tool that
# fails by doing nothing is worse than one that hangs, because the hang is at
# least visible.
#
# Usage:  scripts/make_pdf.sh Project_Overview.md [timeout-seconds]

set -euo pipefail

SRC="${1:?usage: make_pdf.sh <file.md> [timeout-seconds]}"
DEADLINE="${2:-90}"
OUT="${SRC%.md}.pdf"

[ -f "$SRC" ] || { echo "no such file: $SRC" >&2; exit 1; }

MD_TO_PDF="${MD_TO_PDF:-$(command -v md-to-pdf || true)}"
# The nvm-installed path, since a non-interactive shell often misses it.
if [ -z "$MD_TO_PDF" ] && [ -x "$HOME/.nvm/versions/node/v22.20.0/bin/md-to-pdf" ]; then
    MD_TO_PDF="$HOME/.nvm/versions/node/v22.20.0/bin/md-to-pdf"
fi

# Record the pre-run state so a silent no-op cannot pass as success. That is the
# weasyprint failure mode and it is worth guarding against generically rather
# than trusting any one tool to report its own failure.
before_mtime=0
[ -f "$OUT" ] && before_mtime=$(stat -f %m "$OUT" 2>/dev/null || stat -c %Y "$OUT")

if [ -n "$MD_TO_PDF" ]; then
    echo "==> md-to-pdf (deadline ${DEADLINE}s)"
    "$MD_TO_PDF" "$SRC" >/dev/null 2>&1 &
    pid=$!
    waited=0
    # No `timeout` on stock macOS, so poll. Portable, and good enough for a
    # deadline measured in tens of seconds.
    while kill -0 "$pid" 2>/dev/null && [ "$waited" -lt "$DEADLINE" ]; do
        sleep 2
        waited=$((waited + 2))
    done
    if kill -0 "$pid" 2>/dev/null; then
        echo "    stalled after ${DEADLINE}s — killing and falling back"
        kill -9 "$pid" 2>/dev/null || true
        # Chrome is what actually hangs, and it outlives the node wrapper.
        pkill -f "md-to-pdf" 2>/dev/null || true
    else
        wait "$pid" 2>/dev/null || true
        after_mtime=$(stat -f %m "$OUT" 2>/dev/null || stat -c %Y "$OUT" 2>/dev/null || echo 0)
        if [ -f "$OUT" ] && [ "$after_mtime" != "$before_mtime" ]; then
            echo "==> wrote $OUT ($(wc -c < "$OUT" | tr -d ' ') bytes) via md-to-pdf"
            exit 0
        fi
        echo "    produced no new file — falling back"
    fi
fi

echo "==> pandoc --pdf-engine=tectonic"
pandoc "$SRC" --pdf-engine=tectonic -o "$OUT" 2>&1 | grep -v "^warning:" || true

after_mtime=$(stat -f %m "$OUT" 2>/dev/null || stat -c %Y "$OUT" 2>/dev/null || echo 0)
if [ ! -f "$OUT" ] || [ "$after_mtime" = "$before_mtime" ]; then
    echo "FAILED: $OUT was not regenerated by either path" >&2
    exit 1
fi
echo "==> wrote $OUT ($(wc -c < "$OUT" | tr -d ' ') bytes) via pandoc/tectonic"
echo "    NOTE: LaTeX typesetting, visibly different from the md-to-pdf styling."
echo "    WARNING: the default LaTeX font DROPS characters it lacks rather than"
echo "    substituting — U+2248 (approx) is one, and this document uses it. The"
echo "    fallback therefore loses content, not just appearance. Re-run without"
echo "    the fallback before shipping a PDF anyone will read closely, or add"
echo "    --pdf-engine-opt to select a Unicode-capable font."
