# CMake generated Testfile for 
# Source directory: /Users/atharva/Quant Projects/Order Book/tests
# Build directory: /Users/atharva/Quant Projects/Order Book/build-tsan/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
include("/Users/atharva/Quant Projects/Order Book/build-tsan/tests/UnitTests[1]_include.cmake")
include("/Users/atharva/Quant Projects/Order Book/build-tsan/tests/BenchmarkRegression[1]_include.cmake")
add_test(ManualTest "/Users/atharva/Quant Projects/Order Book/build-tsan/tests/ManualTest")
set_tests_properties(ManualTest PROPERTIES  LABELS "project;functional" TIMEOUT "120" _BACKTRACE_TRIPLES "/Users/atharva/Quant Projects/Order Book/tests/CMakeLists.txt;34;add_test;/Users/atharva/Quant Projects/Order Book/tests/CMakeLists.txt;0;")
add_test(StressTest "/Users/atharva/Quant Projects/Order Book/build-tsan/tests/StressTest")
set_tests_properties(StressTest PROPERTIES  LABELS "project;stress" TIMEOUT "120" _BACKTRACE_TRIPLES "/Users/atharva/Quant Projects/Order Book/tests/CMakeLists.txt;41;add_test;/Users/atharva/Quant Projects/Order Book/tests/CMakeLists.txt;0;")
add_test(JournalCrashTest "/Users/atharva/Quant Projects/Order Book/build-tsan/tests/JournalCrashTest")
set_tests_properties(JournalCrashTest PROPERTIES  LABELS "project;recovery" TIMEOUT "120" _BACKTRACE_TRIPLES "/Users/atharva/Quant Projects/Order Book/tests/CMakeLists.txt;55;add_test;/Users/atharva/Quant Projects/Order Book/tests/CMakeLists.txt;0;")
add_test(GatewayIntegrationTest "/Users/atharva/Quant Projects/Order Book/build-tsan/tests/GatewayIntegrationTest")
set_tests_properties(GatewayIntegrationTest PROPERTIES  LABELS "project;integration" TIMEOUT "120" _BACKTRACE_TRIPLES "/Users/atharva/Quant Projects/Order Book/tests/CMakeLists.txt;62;add_test;/Users/atharva/Quant Projects/Order Book/tests/CMakeLists.txt;0;")
add_test(FixTcpGatewayTest "/Users/atharva/Quant Projects/Order Book/build-tsan/tests/FixTcpGatewayTest")
set_tests_properties(FixTcpGatewayTest PROPERTIES  LABELS "project;integration" TIMEOUT "60" _BACKTRACE_TRIPLES "/Users/atharva/Quant Projects/Order Book/tests/CMakeLists.txt;69;add_test;/Users/atharva/Quant Projects/Order Book/tests/CMakeLists.txt;0;")
add_test(SubmitResultTest "/Users/atharva/Quant Projects/Order Book/build-tsan/tests/SubmitResultTest")
set_tests_properties(SubmitResultTest PROPERTIES  LABELS "project;api" TIMEOUT "120" _BACKTRACE_TRIPLES "/Users/atharva/Quant Projects/Order Book/tests/CMakeLists.txt;76;add_test;/Users/atharva/Quant Projects/Order Book/tests/CMakeLists.txt;0;")
add_test(SnapshotConsistencyTest "/Users/atharva/Quant Projects/Order Book/build-tsan/tests/SnapshotConsistencyTest")
set_tests_properties(SnapshotConsistencyTest PROPERTIES  LABELS "project;property" TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/atharva/Quant Projects/Order Book/tests/CMakeLists.txt;83;add_test;/Users/atharva/Quant Projects/Order Book/tests/CMakeLists.txt;0;")
add_test(PropertyTest "/Users/atharva/Quant Projects/Order Book/build-tsan/tests/PropertyTest")
set_tests_properties(PropertyTest PROPERTIES  LABELS "project;property" TIMEOUT "180" _BACKTRACE_TRIPLES "/Users/atharva/Quant Projects/Order Book/tests/CMakeLists.txt;91;add_test;/Users/atharva/Quant Projects/Order Book/tests/CMakeLists.txt;0;")
add_test(JournalReplayPropertyTest "/Users/atharva/Quant Projects/Order Book/build-tsan/tests/JournalReplayPropertyTest")
set_tests_properties(JournalReplayPropertyTest PROPERTIES  LABELS "project;property" TIMEOUT "60" _BACKTRACE_TRIPLES "/Users/atharva/Quant Projects/Order Book/tests/CMakeLists.txt;98;add_test;/Users/atharva/Quant Projects/Order Book/tests/CMakeLists.txt;0;")
add_test(FaultInjectorTest "/Users/atharva/Quant Projects/Order Book/build-tsan/tests/FaultInjectorTest")
set_tests_properties(FaultInjectorTest PROPERTIES  LABELS "project;chaos" TIMEOUT "60" _BACKTRACE_TRIPLES "/Users/atharva/Quant Projects/Order Book/tests/CMakeLists.txt;106;add_test;/Users/atharva/Quant Projects/Order Book/tests/CMakeLists.txt;0;")
add_test(PoolExhaustionTest "/Users/atharva/Quant Projects/Order Book/build-tsan/tests/PoolExhaustionTest")
set_tests_properties(PoolExhaustionTest PROPERTIES  LABELS "project;chaos" TIMEOUT "60" _BACKTRACE_TRIPLES "/Users/atharva/Quant Projects/Order Book/tests/CMakeLists.txt;113;add_test;/Users/atharva/Quant Projects/Order Book/tests/CMakeLists.txt;0;")
add_test(JournalChaosTest "/Users/atharva/Quant Projects/Order Book/build-tsan/tests/JournalChaosTest")
set_tests_properties(JournalChaosTest PROPERTIES  LABELS "project;chaos" TIMEOUT "60" _BACKTRACE_TRIPLES "/Users/atharva/Quant Projects/Order Book/tests/CMakeLists.txt;121;add_test;/Users/atharva/Quant Projects/Order Book/tests/CMakeLists.txt;0;")
add_test(JournalCorruptionTest "/Users/atharva/Quant Projects/Order Book/build-tsan/tests/JournalCorruptionTest")
set_tests_properties(JournalCorruptionTest PROPERTIES  LABELS "project;chaos" TIMEOUT "60" _BACKTRACE_TRIPLES "/Users/atharva/Quant Projects/Order Book/tests/CMakeLists.txt;128;add_test;/Users/atharva/Quant Projects/Order Book/tests/CMakeLists.txt;0;")
add_test(GatewayChaosTest "/Users/atharva/Quant Projects/Order Book/build-tsan/tests/GatewayChaosTest")
set_tests_properties(GatewayChaosTest PROPERTIES  LABELS "project;chaos" TIMEOUT "90" _BACKTRACE_TRIPLES "/Users/atharva/Quant Projects/Order Book/tests/CMakeLists.txt;135;add_test;/Users/atharva/Quant Projects/Order Book/tests/CMakeLists.txt;0;")
add_test(QueueChaosTest "/Users/atharva/Quant Projects/Order Book/build-tsan/tests/QueueChaosTest")
set_tests_properties(QueueChaosTest PROPERTIES  LABELS "project;chaos" TIMEOUT "60" _BACKTRACE_TRIPLES "/Users/atharva/Quant Projects/Order Book/tests/CMakeLists.txt;142;add_test;/Users/atharva/Quant Projects/Order Book/tests/CMakeLists.txt;0;")
add_test(CheckpointChaosTest "/Users/atharva/Quant Projects/Order Book/build-tsan/tests/CheckpointChaosTest")
set_tests_properties(CheckpointChaosTest PROPERTIES  LABELS "project;chaos" TIMEOUT "60" _BACKTRACE_TRIPLES "/Users/atharva/Quant Projects/Order Book/tests/CMakeLists.txt;149;add_test;/Users/atharva/Quant Projects/Order Book/tests/CMakeLists.txt;0;")
add_test(CombinedChaosTest "/Users/atharva/Quant Projects/Order Book/build-tsan/tests/CombinedChaosTest")
set_tests_properties(CombinedChaosTest PROPERTIES  LABELS "project;chaos" TIMEOUT "120" _BACKTRACE_TRIPLES "/Users/atharva/Quant Projects/Order Book/tests/CMakeLists.txt;156;add_test;/Users/atharva/Quant Projects/Order Book/tests/CMakeLists.txt;0;")
subdirs("../_deps/googletest-build")
